version: '3.7'
services:
  zk:
    hostname: zk
    container_name: zk
    image: confluentinc/cp-zookeeper:5.5.1 
    ports: 
      - "2181:2181"
      - "2888:2888"
      - "3888:3888"
    environment:
      TZ: Asia/Bangkok
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_DATA_DIR: /var/lib/zookeeper/data
      ZOOKEEPER_LOG_DIR: /var/lib/zookeeper/log
      ZOOKEEPER_SERVERS: zk:2888:3888
    volumes:
      - D:\My_Work\Git\Kafka_SpringBoot\volumes\zk\data:/var/lib/zookeeper/data
      - D:\My_Work\Git\Kafka_SpringBoot\volumes\zk\log:/var/lib/zookeeper/log

  kafka:
    hostname: kafka
    container_name: kafka
    image: confluentinc/cp-kafka:5.5.1
    ports:
      - "9092:9092"
    environment:
      TZ: Asia/Bangkok
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zk:2181
      KAFKA_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
    volumes:
      - D:\My_Work\Git\Kafka_SpringBoot\volumes\kafka:/var/lib/kafka/data
    depends_on: 
      - zk