version: '3.7'
services:
  zk:
    hostname: zk
    container_name: zk
    image: confluentinc/cp-zookeeper:5.5.1 
    ports: 
      - "2181:2181"
      - "2888:2888"
      - "3888:3888"
    environment:
      TZ: Asia/Bangkok
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
      ZOOKEEPER_DATA_DIR: /var/lib/zookeeper/data
      ZOOKEEPER_LOG_DIR: /var/lib/zookeeper/log
      ZOOKEEPER_SERVERS: zk:2888:3888
      KAFKA_OPTS: -Dzookeeper.client.secure=false
             -Dzookeeper.admin.enableServer=false
    volumes:
      - D:\My_Work\Git\Kafka_SpringBoot\volumes\zk\data:/var/lib/zookeeper/data
      - D:\My_Work\Git\Kafka_SpringBoot\volumes\zk\log:/var/lib/zookeeper/log
    extra_hosts:
      - "zk kafka:192.168.0.36"

  kafka:
    hostname: kafka
    container_name: kafka
    image: confluentinc/cp-kafka:5.5.1
    ports:
      - "9092:9092"
    environment:
      TZ: Asia/Bangkok
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zk:2181
      KAFKA_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CONFLUENT_SUPPORT_METRICS_ENABLE: "false"
      KAFKA_LOG_DIRS: /var/lib/kafka/data
      KAFKA_NUM_PARTITIONS: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"
      KAFKA_DELETE_TOPIC_ENABLE: "true"
      KAFKA_METADATA_MAX_AGE_MS: 180000
      KAFKA_MIN_INSYNC_REPLICAS: 1
      KAFKA_NUM_REPLICA_FETCHERS: 1 
    volumes:
      - D:\My_Work\Git\Kafka_SpringBoot\volumes\kafka:/var/lib/kafka/data
    extra_hosts:
      - "zk kafka:192.168.0.36"
    depends_on: 
      - zk